export const ADD_TODO = 'ADD_TODO';
export const FETCH_TODOLIST = 'FETCH_TODOLIST';
export const DELETE_TODOLIST = 'DELETE_TODOLIST';
export const FETCH_TODO = 'FETCH_TODO';
export const COMPLETED_TODO = ' COMPLETED_TODO';
